select
    {{ clean_text('idpozo') }} as idpozo,
    {{ clean_text('sigla') }} as sigla,
    {{ clean_text('formprod') }} as formprod,
    {{ clean_text('idempresa') }} as idempresa,
    {{ clean_text('idareapermisoconcesion') }} as idareapermisoconcesion,
    {{ clean_text('areapermisoconcesion') }} as areapermisoconcesion,
    {{ clean_text('idareayacimiento') }} as idareayacimiento,
    {{ clean_text('areayacimiento') }} as areayacimiento,
    {{ clean_text('idcuenca') }} as idcuenca,
    {{ clean_text('cuenca') }} as cuenca,
    {{ clean_text('idprovincia') }} as idprovincia,
    {{ clean_text('provincia') }} as provincia,
    {{ clean_text('codigopropio') }} as codigopropio,
    {{ clean_text('nombrepropio') }} as nombrepropio,
    {{ to_numeric('coordenadax') }} as coordenadax,
    {{ to_numeric('coordenaday') }} as coordenaday,
    {{ to_numeric('cota') }} as cota,
    {{ to_numeric('profundidad') }} as profundidad,
    {{ to_numeric('petroleo') }} as petroleo,
    {{ to_numeric('gas') }} as gas,
    {{ to_numeric('agua') }} as agua,
    {{ to_numeric('periodo') }} as periodo,
    {{ to_numeric('pet_inicial') }} as pet_inicial,
    {{ to_numeric('gas_inicial') }} as gas_inicial,
    {{ to_numeric('agua_inicial') }} as agua_inicial,
    {{ to_numeric('iny_agua_inicial') }} as iny_agua_inicial,
    {{ to_numeric('iny_gas_inicial') }} as iny_gas_inicial,
    {{ to_numeric('iny_co2_inicial') }} as iny_co2_inicial,
    {{ to_numeric('iny_otros_inicial') }} as iny_otros_inicial,
    {{ to_numeric('vida_util_inicial') }} as vida_util_inicial,
    {{ to_date('fecha_data') }} as fecha_data,
    {{ to_date('fechadeingreso') }} as fechadeingreso,
    {{ clean_text('gasplus') }} as gasplus,
    {{ clean_text('clasificacion') }} as clasificacion,
    {{ clean_text('subclasificacion') }} as subclasificacion,
    {{ clean_text('tipo_reservorio') }} as tipo_reservorio,
    {{ clean_text('subtipo_reservorio') }} as subtipo_reservorio,
    {{ clean_text('comp_perf') }} as comp_perf,
    {{ clean_text('unique_sigla_formprod') }} as unique_sigla_formprod,
    {{ clean_text('adjiv_comp_perf') }} as adjiv_comp_perf,
    {{ to_numeric('adjiv_capacidad_perf') }} as adjiv_capacidad_perf,
    {{ to_date('adjiv_fecha_inicio') }} as adjiv_fecha_inicio,
    {{ to_date('adjiv_fecha_fin') }} as adjiv_fecha_fin,
    {{ to_date('adjiv_fecha_abandono') }} as adjiv_fecha_abandono,
    {{ to_date('adjiv_fecha_inicio_term') }} as adjiv_fecha_inicio_term,
    {{ to_date('adjiv_fecha_fin_term') }} as adjiv_fecha_fin_term,
    {{ clean_text('adjiv_clasificacion') }} as adjiv_clasificacion,
    {{ clean_text('adjiv_subclasificacion') }} as adjiv_subclasificacion,
    {{ clean_text('adjiv_tipo_reservorio') }} as adjiv_tipo_reservorio,
    {{ clean_text('adjiv_subtipo_reservorio') }} as adjiv_subtipo_reservorio,
    {{ clean_text('adjiv_equipo_utilizar') }} as adjiv_equipo_utilizar,
    _run_id,
    _source_name,
    _source_url,
    _source_file_hash,
    _ingested_at,
    _raw_row_number
from {{ ref('stg_pozos_operadoras') }}
