select
    produccion_id,
    fecha_mes,
    md5(coalesce(idpozo, '')) as pozo_id,
    md5(coalesce(idempresa, '')) as operadora_id,
    md5(coalesce(idareapermisoconcesion, '')) as area_id,
    md5(coalesce(idareayacimiento, '')) as yacimiento_id,
    idpozo,
    idempresa,
    idareapermisoconcesion,
    idareayacimiento,
    prod_pet,
    prod_gas,
    prod_agua,
    iny_agua,
    iny_gas,
    iny_co2,
    iny_otro,
    tef,
    vida_util,
    _run_id,
    _source_file_hash,
    _ingested_at
from {{ ref('produccion_no_convencional') }}
