select
    raw_payload ->> 'anio' as anio,
    raw_payload ->> 'mes' as mes,
    raw_payload ->> 'idpozo' as idpozo,
    raw_payload ->> 'idempresa' as idempresa,
    raw_payload ->> 'empresa' as empresa,
    raw_payload ->> 'sigla' as sigla,
    raw_payload ->> 'formprod' as formprod,
    raw_payload ->> 'cuenca' as cuenca,
    raw_payload ->> 'provincia' as provincia,
    raw_payload ->> 'idareapermisoconcesion' as idareapermisoconcesion,
    raw_payload ->> 'areapermisoconcesion' as areapermisoconcesion,
    raw_payload ->> 'idareayacimiento' as idareayacimiento,
    raw_payload ->> 'areayacimiento' as areayacimiento,
    raw_payload ->> 'formacion' as formacion,
    raw_payload ->> 'tipo_de_recurso' as tipo_de_recurso,
    raw_payload ->> 'sub_tipo_recurso' as sub_tipo_recurso,
    raw_payload ->> 'clasificacion' as clasificacion,
    raw_payload ->> 'subclasificacion' as subclasificacion,
    raw_payload ->> 'tipoextraccion' as tipoextraccion,
    raw_payload ->> 'tipoestado' as tipoestado,
    raw_payload ->> 'tipopozo' as tipopozo,
    raw_payload ->> 'proyecto' as proyecto,
    raw_payload ->> 'prod_pet' as prod_pet,
    raw_payload ->> 'prod_gas' as prod_gas,
    raw_payload ->> 'prod_agua' as prod_agua,
    raw_payload ->> 'iny_agua' as iny_agua,
    raw_payload ->> 'iny_gas' as iny_gas,
    raw_payload ->> 'iny_co2' as iny_co2,
    raw_payload ->> 'iny_otro' as iny_otro,
    raw_payload ->> 'tef' as tef,
    raw_payload ->> 'vida_util' as vida_util,
    raw_payload ->> 'profundidad' as profundidad,
    raw_payload ->> 'coordenadax' as coordenadax,
    raw_payload ->> 'coordenaday' as coordenaday,
    raw_payload ->> 'fecha_data' as fecha_data,
    raw_payload ->> 'fechaingreso' as fechaingreso,
    raw_payload ->> 'habilitado' as habilitado,
    raw_payload ->> 'rectificado' as rectificado,
    raw_payload ->> 'observaciones' as observaciones,
    raw_payload ->> 'idusuario' as idusuario,
    _run_id,
    _source_name,
    _source_url,
    _source_file_hash,
    _ingested_at,
    _raw_row_number
from {{ source('bronze', 'raw_produccion_no_convencional') }}
