select
    raw_payload ->> 'idpozo' as idpozo,
    raw_payload ->> 'sigla' as sigla,
    raw_payload ->> 'formprod' as formprod,
    raw_payload ->> 'idempresa' as idempresa,
    raw_payload ->> 'idareapermisoconcesion' as idareapermisoconcesion,
    raw_payload ->> 'areapermisoconcesion' as areapermisoconcesion,
    raw_payload ->> 'idareayacimiento' as idareayacimiento,
    raw_payload ->> 'areayacimiento' as areayacimiento,
    raw_payload ->> 'idcuenca' as idcuenca,
    raw_payload ->> 'cuenca' as cuenca,
    raw_payload ->> 'idprovincia' as idprovincia,
    raw_payload ->> 'provincia' as provincia,
    raw_payload ->> 'codigopropio' as codigopropio,
    raw_payload ->> 'nombrepropio' as nombrepropio,
    raw_payload ->> 'coordenadax' as coordenadax,
    raw_payload ->> 'coordenaday' as coordenaday,
    raw_payload ->> 'cota' as cota,
    raw_payload ->> 'profundidad' as profundidad,
    raw_payload ->> 'petroleo' as petroleo,
    raw_payload ->> 'gas' as gas,
    raw_payload ->> 'agua' as agua,
    raw_payload ->> 'periodo' as periodo,
    raw_payload ->> 'pet_inicial' as pet_inicial,
    raw_payload ->> 'gas_inicial' as gas_inicial,
    raw_payload ->> 'agua_inicial' as agua_inicial,
    raw_payload ->> 'iny_agua_inicial' as iny_agua_inicial,
    raw_payload ->> 'iny_gas_inicial' as iny_gas_inicial,
    raw_payload ->> 'iny_co2_inicial' as iny_co2_inicial,
    raw_payload ->> 'iny_otros_inicial' as iny_otros_inicial,
    raw_payload ->> 'vida_util_inicial' as vida_util_inicial,
    raw_payload ->> 'fecha_data' as fecha_data,
    raw_payload ->> 'fechadeingreso' as fechadeingreso,
    raw_payload ->> 'gasplus' as gasplus,
    raw_payload ->> 'clasificacion' as clasificacion,
    raw_payload ->> 'subclasificacion' as subclasificacion,
    raw_payload ->> 'tipo_reservorio' as tipo_reservorio,
    raw_payload ->> 'subtipo_reservorio' as subtipo_reservorio,
    raw_payload ->> 'comp_perf' as comp_perf,
    raw_payload ->> 'unique_sigla_formprod' as unique_sigla_formprod,
    raw_payload ->> 'adjiv_comp_perf' as adjiv_comp_perf,
    raw_payload ->> 'adjiv_capacidad_perf' as adjiv_capacidad_perf,
    raw_payload ->> 'adjiv_fecha_inicio' as adjiv_fecha_inicio,
    raw_payload ->> 'adjiv_fecha_fin' as adjiv_fecha_fin,
    raw_payload ->> 'adjiv_fecha_abandono' as adjiv_fecha_abandono,
    raw_payload ->> 'adjiv_fecha_inicio_term' as adjiv_fecha_inicio_term,
    raw_payload ->> 'adjiv_fecha_fin_term' as adjiv_fecha_fin_term,
    raw_payload ->> 'adjiv_clasificacion' as adjiv_clasificacion,
    raw_payload ->> 'adjiv_subclasificacion' as adjiv_subclasificacion,
    raw_payload ->> 'adjiv_tipo_reservorio' as adjiv_tipo_reservorio,
    raw_payload ->> 'adjiv_subtipo_reservorio' as adjiv_subtipo_reservorio,
    raw_payload ->> 'adjiv_equipo_utilizar' as adjiv_equipo_utilizar,
    _run_id,
    _source_name,
    _source_url,
    _source_file_hash,
    _ingested_at,
    _raw_row_number
from {{ source('bronze', 'raw_pozos_operadoras') }}
